title: Yutong Li # your name (or website title) here
logo: "/images/200px-Alstroemeria_Records_icon.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  The University of British Columbia
  <br><br>
   2nd Year Combined Major in Computer Science and Statistics
  <br><br>
  <a href="https://www.linkedin.com/in/yutong-lican/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics_code: UA-163293970-1
